[workspace]
authors = ["Noah Jutz <noah@noahjutz.com>"]
channels = ["conda-forge", "robostack-humble"]
name = "3_cyberrunner"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
ros-humble-ros2run = ">=0.18.12,<0.19"
ros-humble-rclpy = ">=3.3.16,<4"
ros-humble-cyberrunner-interfaces = { path = "src/cyberrunner_interfaces" }
ros-humble-cyberrunner-camera = { path = "src/cyberrunner_camera" }
ros-humble-cyberrunner-dynamixel = { path = "src/cyberrunner_dynamixel" }
ros-humble-cyberrunner-state-estimation = { path = "src/cyberrunner_state_estimation" }
ros-humble-cyberrunner-dreamer = { path = "src/cyberrunner_dreamer" }
