[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-ros"
version = "*"

[package.build.config]
distro = "humble"
extra-package-mappings = [
	{ file = "../../mapping.yaml" }
]

[package.host-dependencies]
ros-humble-cyberrunner-interfaces = { path = "../cyberrunner_interfaces" }

[package.build-dependencies]
ros-humble-cyberrunner-interfaces = { path = "../cyberrunner_interfaces" }

[package.run-dependencies]
ros-humble-cyberrunner-interfaces = { path = "../cyberrunner_interfaces" }
